name: Calculate Artifact Downloads

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build.yml"]
    types:
      - completed

jobs:
  calculate-downloads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get Artifacts from Another Repository
        id: artifacts
        run: |
          # Define the owner and repo of the target repository
          TARGET_OWNER="brahmkshatriya"  # Replace with the owner of the target repository
          TARGET_REPO="echo-youtube-extension"  # Replace with the name of the target repository
          
          # Fetch artifacts from the target repository using GitHub API
          artifacts=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$TARGET_OWNER/$TARGET_REPO/actions/artifacts")
          
          # Debug output
          echo "Artifact API response: $artifacts"
          
          # Calculate the total download count, handle null values
          total_downloads=$(echo "$artifacts" | jq '[.artifacts[] | .download_count // 0] | add')
          echo "Total downloads from $TARGET_REPO: $total_downloads"
          echo "total_downloads=$total_downloads" >> $GITHUB_ENV

      - name: Update Downloads JSON
        run: |
          echo '{
            "schemaVersion": 1,
            "label": "downloads",
            "message": "'$total_downloads'",
            "color": "blue"
          }' > downloads.json

      - name: Debug Downloads JSON
        run: |
          cat downloads.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add downloads.json
          git commit -m "Update downloads count"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure this token has write permissions
