name: Calculate Artifact Downloads

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build.yml"]
    types:
      - completed

jobs:
  calculate-downloads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get Artifacts from Another Repository
        id: artifacts
        run: |
          TARGET_OWNER="brahmkshatriya"
          TARGET_REPO="echo-discord"
          
          response=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$TARGET_OWNER/$TARGET_REPO/actions/artifacts")
          
          echo "Artifact API response: $response"
          
          total_downloads=$(echo "$response" | jq '[.artifacts[] | .download_count // 0] | add')
          
          if [ -z "$total_downloads" ]; then
            echo "Failed to calculate total downloads."
            exit 1
          fi

          echo "Total downloads from $TARGET_REPO: $total_downloads"
          echo "total_downloads=$total_downloads" >> $GITHUB_ENV

      - name: Update Downloads JSON
        run: |
          total_downloads=${{ env.total_downloads }}
          echo '{
            "schemaVersion": 1,
            "label": "downloads",
            "message": "'"${total_downloads}"'",
            "color": "blue"
          }' > downloads.json

      - name: Debug Downloads JSON
        run: cat downloads.json

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add downloads.json
          git commit -m "Update downloads count"
          git push
